CREATE TABLE `T_TOKEN` (
`token_id` int(11) NOT NULL AUTO_INCREMENT,
`token` TEXT NOT NULL UNIQUE,
`token_hash` TEXT NOT NULL UNIQUE,
`user_id` int(11) NOT NULL,
`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`token_id`),
FOREIGN KEY (`user_id`) REFERENCES `T_USER`(`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;